
x-api: &api
  image: ghcr.io/jhon2c/rinha-de-backend-2026-zig:1cf6577
  platform: linux/amd64
  network_mode: "none"
  volumes:
    - socks:/run/sock
  ulimits:
    nofile: { soft: 65535, hard: 65535 }
    memlock: { soft: -1, hard: -1 }

services:
  api1:
    <<: *api
    command: ["/server", "/index.bin", "/run/sock/api1.sock", "2", "96", "50", "200"]
    cpuset: "0"
    deploy:
      resources:
        limits: { cpus: "0.495", memory: "165MB" }

  api2:
    <<: *api
    command: ["/server", "/index.bin", "/run/sock/api2.sock", "2", "96", "50", "200"]
    cpuset: "3"
    deploy:
      resources:
        limits: { cpus: "0.495", memory: "165MB" }

  lb:
    image: ghcr.io/jhon2c/rinha-de-backend-2026-zig:1cf6577
    platform: linux/amd64
    command: ["/lb", "9999", "/run/sock/api1.sock", "/run/sock/api2.sock"]
    cpuset: "1,2"
    ports:
      - "9999:9999"
    volumes:
      - socks:/run/sock
    ulimits:
      nofile: { soft: 65535, hard: 65535 }
    depends_on: [api1, api2]
    deploy:
      resources:
        limits: { cpus: "0.01", memory: "16MB" }

volumes:
  socks:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m"
